### ISSUE TITLE
Mac的终端下出错

### ISSUE THREAD

**Issue by sxk000** [pythonstock/stock#3]
博主您好，首先谢谢您的分享！
我按照您的博客运行了代码，结果提示如下：
依赖镜像mariadb可以下载，并启动成功了；
但是tensorflow-stock镜像不能下载，报的是没有找到这样的文件，您没有共享这个文件吗？还是什么原因呢？如果不方便共享的话请告知一下，我就不在继续折腾了（已经折腾大半个月了，查了各种问题又尝试了各种方法，再次谢谢您的分享！）

终端运行报错结果如下：

******deMacBook-Pro:docker ******$ sh startStock.sh  
docker: Error response from daemon: Conflict. The container name "/mariadb" is already in use by container "51f32a994b41c7b7febfd5194447105ad1771de9d51c4d81cf28a9673a5403d2". You have to remove (or rename) that container to be able to reuse that name.  
See 'docker run --help'.  
starting mariadb ...  
wait 10 second , and create stock database .  
mariadb is not running !!!  
starting stock ...  
Unable to find image 'github.com/pythonstock/stock/tensorflow-py3-stock:latest' locally  
docker: Error response from daemon: error parsing HTTP 404 response body: invalid character 'N' looking for beginning of value: "Not Found".  
See 'docker run --help'.  
******deMacBook-Pro:docker ******$

**Comment by JackonLiu** [comment]
博主您好，首先谢谢您的分享！
我按照您的博客运行了代码，结果出现一个bug提示如下：
date (NVARCHAR(255)) not a string

**Comment by winglight** [comment]
这个问题我碰到过，docker run那个命令不能重复运行，启动container要用docker start

我碰到的问题是，启动container时报错：chown: changing ownership of '/var/lib/mysql/': Operation not permitted
