### ISSUE TITLE
maria docker的端口和本地mysql冲突了

### ISSUE THREAD

**Issue by winglight** [pythonstock/stock#5]
docker这个端口能否修改呢？

**Comment by winglight** [comment]
这问题算是解决了吧，不过，还有新的问题：
1.在本地（mac）部署可以正常运行，有股票数据
2.在VPS（ubuntu）部署也可以运行，但是数据库只创建了schema没有创建table，我手动创建了tables之后，还以为会自动导入数据，结果重启几次都还是没有数据

**Comment by zktc5418** [comment]
@winglight  我在mac端运行 数据库链接 一直失败

**Comment by golangpkg** [comment]
已经更新了镜像，
解决这个问题了。

进入镜像：
```
docker exec -it stock bash 
sh /data/stock/jobs/cron.daily/run_daily
```

**Comment by liyuchong2099** [comment]
![image](https://user-images.githubusercontent.com/39976496/87247775-5b06f380-c488-11ea-941e-e9b16ebaf30b.png)
mac 中运行，不能连接数据库。
