### ISSUE TITLE
有没有非docker部署方式啊

### ISSUE THREAD

**Issue by royburns** [pythonstock/stock#6]
个人笔记本电脑，windows平台，用docker不是很方便，能否提供一下普通的python应用部署方式指导，提供一下数据库之类的配置文件，谢谢了

**Comment by golangpkg** [comment]
在安装 python 的环境中，有肯能不通 linux 安装 lib包多少会有些差异。
使用docker 这样的方式能最大的解决这些繁琐的部署安装问题。可以看下DockerFile 。自己进行安装。
